### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ecksun** [ember-mobile/ember-cli-fastclick#13]
I'm having issues using ember-cli-fastclick, it appears to be lacking dependencies (as everything is defined as devDependencies).

It appears that in the latest version of ember-cli broccoli-stew is included because ember-cli depends on it, but I'm running an older version of ember-cli which cases the issue.

Regardless, all dependencies that are required for the library to run should be defined as `dependencies` and not `devDependencies`

```
ember install ember-cli-fastclick
Cannot find module 'broccoli-stew'
Error: Cannot find module 'broccoli-stew'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/code/project/node_modules/ember-cli-fastclick/index.js:7:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by spieker** [comment]
Hey @ecksun, thanks for the information. I've just tested it with

```
ember-cli: 2.13.2 and 2.16.2
node: 6.3.1
os: darwin x64
```
and it just works for me. Could you please provide me with more details?

Best,
Paul

**Comment by ecksun** [comment]
> Could you please provide me with more details?

The issue is that you have undefined dependencies, the reason it works is because ember-cli have other dependencies that include the ones required for this module.

Basically it will only work with ember-cli versions that happen to have the same dependencies as ember-cli-fastclick. The library [clearly depends on broccoli-stew](https://github.com/ember-mobile/ember-cli-fastclick/blob/master/index.js#L7) and should thus declare it as a dependency.

Here is a way to reproduce the issue:

```
cd $(mktemp -d)
npm init -y
npm install ember-cli@1.13.8
./node_modules/.bin/ember install ember-cli-fastclick
```

**Comment by spieker** [comment]
It should be defined as a dependency, you're right. Sorry, that it took so long!

**Comment by lawitschka** [comment]
@spieker @ecksun Version 1.4.1 including the dependency fix has just been published
